class Registry:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def histogram_add(
        self,
        *,
        name: str,
        help: str,
        buckets: list[float],
    ) -> None: ...
    def histogram_observe(
        self,
        name: str,
        labels: list[tuple[str, str]] | dict[str, str],
        val: float,
    ) -> None: ...
    def histogram_list(self) -> list[str]: ...
    def encode(self) -> str: ...
